### ISSUE TITLE
What's the supposed key size?

### ISSUE THREAD

**Issue by pepyakin** [chjj/liburkel#4]
Looking at example/cli code it seems that the only key length used is 32 bytes long. Is this maximum? My quick experiment shows that it is _possible_ (as in it doesn't explode in my face) to use other key sizes.

**Comment by chjj** [comment]
Yes. The key size is configurable via `internal.h`. I haven't tested it, but various code paths _should_ account for it properly (fingers crossed).

That said, I don't recommend using anything other than 256 bit keys. Lower is risky security-wise, and higher is overkill.

**Comment by pepyakin** [comment]
Thanks! Just stumbled on this file.

I think it would've been great if it were in mentioned in api docs.

**Comment by calvin2021y** [comment]
hi @chjj , thanks for the great work.

If I use liburkel as a sqlite page storage, the page_id could be 4 byte or 8 byte,  will it be safe for this use case by change size from internal.h ? (should I always use hash function for page_id ?) （page_id as key, from 1 to 2^63-1 ）
